
plugins:
  - jekyll-relative-links

title: Roger Paredes

relative_links:
  enabled: true
  collections: true

remote_theme: jekyll/minima

minima:
  social_links:
    twitter: paredesrogerl
    github: paredesroger
    linkedin: paredesroger

# Google Analytics
google_analytics: UA-226927214-1
